spring:
  application:
    name: demo-orchestrator

coordinator:
  base-url: http://localhost:8081

order-service:
  base-url: http://localhost:8083

payment-service:
  base-url: http://localhost:8084

inventory-service:
  base-url: http://localhost:8085

server:
  port: 8082
