spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

coordinator:
  base-url: http://localhost:8081

server:
  port: 8084
